//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twidlle.KeyboardTrainer.WinFormsApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Twidlle.KeyboardTrainer.WinFormsApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to finish current workout?.
        /// </summary>
        internal static string AskClose {
            get {
                return ResourceManager.GetString("AskClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current workout?.
        /// </summary>
        internal static string AskSaveFile {
            get {
                return ResourceManager.GetString("AskSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyboardTrainer Error.
        /// </summary>
        internal static string ExceptionDialogCaption {
            get {
                return ResourceManager.GetString("ExceptionDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      KeyboardTrainer version: {0}
        ///.Net Framework version: {1}
        ///            OS Version: {2},
        ///           Is 64Bit OS: {3},
        ///      Is 64Bit Process: {4},
        ///
        ///Modules: 
        ///{5}
        ///
        ///Stack Trace:
        ///{6}.
        /// </summary>
        internal static string ExceptionDialogDetailsFormat {
            get {
                return ResourceManager.GetString("ExceptionDialogDetailsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///Clipboard contains details of error..
        /// </summary>
        internal static string ExceptionDialogMessageFormat {
            get {
                return ResourceManager.GetString("ExceptionDialogMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.twidlle.com/keyboardtrainer/index.html.
        /// </summary>
        internal static string HelpUrl {
            get {
                return ResourceManager.GetString("HelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string LanguageCode {
            get {
                return ResourceManager.GetString("LanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New exercise.
        /// </summary>
        internal static string NewExercise {
            get {
                return ResourceManager.GetString("NewExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Noname workout].
        /// </summary>
        internal static string NoNameFileName {
            get {
                return ResourceManager.GetString("NoNameFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open workout file.
        /// </summary>
        internal static string OpenWorkoutFile {
            get {
                return ResourceManager.GetString("OpenWorkoutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyboardTrainer workout
        ///----------------------------------------------------------
        ///               Workout date: {0}
        ///               Workout plan: {1}
        ///             Local language: {2}
        ///         Executed exercises: {3}
        ///    Best result of exercise: {4} char/min, {5} errors
        ///    Result of last exercise: {8} char/min, {9} errors
        ///Average result of exercises: {6:##.##} char/min, {7:##.##} errors.
        /// </summary>
        internal static string ResultFormat {
            get {
                return ResourceManager.GetString("ResultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string RunningState {
            get {
                return ResourceManager.GetString("RunningState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save workout file.
        /// </summary>
        internal static string SaveWorkoutFile {
            get {
                return ResourceManager.GetString("SaveWorkoutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        internal static string SpaceVoiceText {
            get {
                return ResourceManager.GetString("SpaceVoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout files (*.ktr)|*.ktr|All files (*.*)|*.*.
        /// </summary>
        internal static string WorkoutFileFilter {
            get {
                return ResourceManager.GetString("WorkoutFileFilter", resourceCulture);
            }
        }
    }
}
